{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form action={'ezjscore/call'|ezurl} method="post" class="ajaxuploader-location">
    <fieldset>
        {def
            $upload_class_map        = ezini( 'CreateSettings', 'MimeClassMap', 'upload.ini' )
            $upload_class_attribute  = ezini( concat( $upload_class_map['image'], '_ClassSettings' ), 'FileAttribute', 'upload.ini' )
            $alt_text_required       = false()
        }

        {if $class.identifier|eq( $upload_class_map['image'] )}
            {def $has_alternative_text = true()}
            {if $class.data_map[$upload_class_attribute].data_int2}
                {set $alt_text_required = true()}
            {/if}
        {else}
            {def $has_alternative_text = false()}
        {/if}

        <legend>{"Step 2/3: Choose a location for the new '%class' object."|i18n( 'design/admin/ajaxuploader', '', hash( '%class', $class.name|wash() ) )}{if $alt_text_required} {'The alternative text field is required.'|i18n( 'design/admin/ajaxuploader' )}{/if}</legend>
        <p>{'<em>%file</em> has successfully been uploaded.'|i18n( 'design/admin/ajaxupload', '', hash( '%file', $file.original_filename|wash() ) )}</p>

        {if $has_alternative_text}
            <p>
                <label for="alt_text_entry">{'Alternative text'|i18n( 'design/admin/ajaxuploader' )}{if $alt_text_required} {'(required)'|i18n( 'design/admin/ajaxuploader' )}{/if}:</label>
                <input{if $alt_text_required} required class="input-required"{/if} id="UploadAlternativeText" name="UploadAlternativeText" size="70">
            </p>
        {/if}

        <p>{"Please choose a location for the '%class' object that is going to be created from it."|i18n( 'design/admin/ajaxuploader', '', hash( '%class', $class.name|wash() ) )}</p>
        <div class="ajaxuploader-browse">
            {include uri="design:ajaxuploader/browse.tpl" browse_start=$browse_start class=$class browse=$browse default_parent_node=$default_parent_node}
        </div>

        <p class="ajaxuploader-button-bar">
            <input type="hidden" name="UploadOriginalFilename" value="{$file.original_filename|wash()}" />
            <input type="hidden" name="UploadName" value="{$name|wash()}" />
            <input type="hidden" name="UploadFile" value="{$file.filename|wash()}" />
            <input type="submit" class="defaultbutton" value="{'Choose this location'|i18n( 'design/admin/ajaxuploader' )}" />
            <a href="#" class="window-cancel">{'Close'|i18n( 'design/admin/ajaxuploader' )}</a>
            <span class="ajaxuploader-error"></span>
        </p>
    </fieldset>
</form>
